name: CI - Lint & Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18 # or whatever you're using

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build

      # Optional: run tests if you have them
      - name: Run tests
        run: npm test
